import Header from "../stories/organisms/Header/Header";
import { Inter } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const headerLinks = [
  {
    title: "Home",
    path: "/",
  },
  {
    title: "About Us",
    path: "/aboutus",
  },
];

const inter = Inter({ subsets: ["latin"], variable: "--inter-font" });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Header links={headerLinks} />
        <>{children}</>
      </body>
    </html>
  );
}
